version: "3.9"  # optional since v1.27.0
services:
  server:
    container_name: server
    image: hungparfait009/server-management-project-final
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo 
      - redis
    environment: 
      PORT: 3000
      DB_CONNECTION_STRING: mongodb://mongo/ServerManagement
      NODE_ENV: production
  redis: 
    container_name: redis
    image: redis
    ports: 
      - 6379:6379
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always